PREP(canContinue);
PREP(displayProgressOnScreen);
PREP(formatEstimatedTimeRemaining);
PREP(formatProgress);
PREP(initDownloadAction);
PREP(initGetPendriveAction);
PREP(prepareDisplay);
PREP(setupSimple);
PREP(start);
