PREP(canContinue);
PREP(displayProgressOnScreen);
PREP(formatEstimatedTimeRemaining);
PREP(formatProgress);
PREP(initDownloadAction);
PREP(initGetDeviceAction);
PREP(prepareDisplay);
PREP(setupSimple);
PREP(start);
