
name = "ArmaForces Mission Framework"
mainprefix = "z"
prefix = "afmf"

[files]
include = [
    "LICENSE",
    "mod.cpp",
    "README.md"
]

exclude = ["*.psd", "*.png", "*.tga"]

[properties]
author = "ArmaForces"

[version]
path = "addons/main/script_version.hpp"
